package pojo.com.hibernate.prueba.pojo;
// Generated 16 nov 2022 13:12:16 by Hibernate Tools 5.5.9.Final

import java.math.BigDecimal;

/**
 * Animales generated by hbm2java
 */
public class Animales implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String habitad;
	private BigDecimal pesoAproximado;

	public Animales() {
	}

	public Animales(String nombre, String habitad, BigDecimal pesoAproximado) {
		this.nombre = nombre;
		this.habitad = habitad;
		this.pesoAproximado = pesoAproximado;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getHabitad() {
		return this.habitad;
	}

	public void setHabitad(String habitad) {
		this.habitad = habitad;
	}

	public BigDecimal getPesoAproximado() {
		return this.pesoAproximado;
	}

	public void setPesoAproximado(BigDecimal pesoAproximado) {
		this.pesoAproximado = pesoAproximado;
	}

}
